name: Chat App CI

env:
  DOCKERHUB_USER: vishnu1111
  
on:
  push:
    branches: [main]

 # ─── JOB 1: Run Tests
jobs: 
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [22,23]
        
    runs-on: ${{matrix.os}}
    
    name: Test on Node ${{ matrix.node-version }} 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend   

      - name: Run backend tests
        run: npm test
        working-directory: ./backend

  # JOB 2: Build & Push Backend, calls resuable workflow
  build-backend:
    needs: test
    uses: ./.github/workflows/docker-build.yml
    with:
      service-name: backend
      docker-image: vishnu1111/chatapp-backend
      build-context: ./backend
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
  
  # JOB 3: Build & Push Frontend
  build-frontend:
    needs: test
    uses: ./.github/workflows/docker-build.yml    
    with:
      service-name: frontend
      docker-image: vishnu1111/chatapp-frontend
      build-context: ./frontend
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
